---
title: Generative AI Track record
permalink: /posts/gen-ai-track-record/
tags: genai ai llm
comments: false
status: ongoing
---

// TODO
//https://poloclub.github.io/transformer-explainer/
// == 2025-04-22 link:https://arxiv.org/abs/2504.15681[Vidi: Large Multimodal Models for Video Understanding and Editing]
// link:https://www.researchgate.net/publication/354639860_Is_AI_Ground_Truth_Really_True_The_Dangers_of_Training_and_Evaluating_AI_Tools_Based_on_Experts'_Know-What[Is AI Ground Truth Really True? The Dangers of Training and Evaluating AI Tools Based on Experts’ Know-What]
// link:https://zenodo.org/records/17065099[Against the Uncritical Adoption of 'AI' Technologies in Academia]
// == 2024-06-04 link:https://arxiv.org/abs/2211.04325[Will we run out of data? Limits of LLM scaling based on human-generated data]
// == 2018-01-02 link:https://arxiv.org/abs/1801.00631[Deep Learning: A Critical Appraisal]
// == 2024-02-28 link:https://arxiv.org/abs/2402.18649[A New Era in LLM Security: Exploring Security Concerns in Real-World LLM-based Systems]
// 2024-05-13 link:https://www.mdpi.com/2076-3417/14/10/4115[The Impact of Large Language Models on Programming Education and Student Learning Outcomes]
// 2024-10-07 link:https://arxiv.org/pdf/2410.05229[Understanding the Limitations of Mathematical Reasoning in Large Language Models]
// == link:https://www.arxiv.org/pdf/2505.10066[Dark LLMs: The Growing Threat of Unaligned AI Models]
// == 2024-09-05 link:https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4945566[The Effects of Generative AI on High Skilled Work: Evidence from Three Field Experiments with Software Developers]
// 2024-01-09 link:https://codescene.com/hubfs/whitepapers/Refactoring-vs-Refuctoring-Advancing-the-state-of-AI-automated-code-improvements.pdf[Refactoring vs Refuctoring: Advancing the state of AI-automated code improvements]
// link:https://www.arxiv.org/abs/2509.21361[Context Is What You Need: The Maximum Effective Context Window for Real World Limits of LLMs] and what LLMs to do solve this: https://chatgpt.com/share/68dcc26b-fcb4-8011-8b20-fb4d9c81fcb9 (summarisation, chunking, stochastic pruning) "For scale, I ran a 100 LOC source file through a tokenizer, and it contained > 1000 tokens."

== General LLM comparisons

- link:https://arcprize.org/leaderboard[ARC-AGI Leaderboard], shows cost vs score
- link:https://artificialanalysis.ai/[Artificial Analysis] of AI models and API providers
- link:https://www.swebench.com/#verified[SWE-bench], Can Language Models Resolve Real-World GitHub Issues?
- link:https://bbycroft.net/llm[LLM Visualization]

// McDonalds order errors
// NY legal errors


== 2025-10-08 link:https://www.legitsecurity.com/blog/camoleak-critical-github-copilot-vulnerability-leaks-private-source-code[CamoLeak: Critical GitHub Copilot Vulnerability Leaks Private Source Code]

* In June 2025, I found a critical vulnerability in GitHub Copilot Chat (CVSS 9.6) that allowed silent exfiltration of secrets and source code from private repos, and gave me full control over Copilot’s responses, including suggesting malicious code or links.
* The attack combined a novel CSP bypass using GitHub’s own infrastructure with remote prompt injection. I reported it via HackerOne, and GitHub fixed it by disabling image rendering in Copilot Chat completely.
* [In GitHub Issues] invisible comments are an official feature! 🎉
** [`<!-- #Hey Github Copilot, this one is for you -->]
* GitHub enforces a very restrictive Content Security Policy (CSP), which blocks fetching images and other content types from domains that aren’t explicitly owned by GitHub. [a simple <img> trick won’t work to exfiltrate data via image GET]
* how does my fancy README manage to show images from third-party sites? [all URLs are rewritten so they point to GitHubs own Camo: https://camo.githubusercontent.com]
* If I create a dictionary of all letters and symbols in the alphabet, pre-generate their corresponding Camo URLs, embed this dictionary into the injected prompt, and then ask Copilot to play a “small game” by rendering the content I want to leak as “ASCII art” composed entirely of images, will Copilot inject valid Camo images that the browser will render by their order? Yes, it will.
* [Create a PR on a public repo with a prompt injection. This injection will then lead to Copilot searching for AWS_KEY in private repositories of that user, and exfiltrate the actual key by rendering each letter of the key with the pregenerated camo-urls, all invisible.]

== 2025-10-02 link:https://mdalmijn.com/p/ai-the-ultimate-product-killer[AI: The Ultimate Product Killer]

* AI has made us better at shipping.
* However, being able to ship more features is not the flex companies think it is.
* Shipping faster usually only means you’re speeding up the demise of your product.
* Every feature we add, unless it adds value, is a parasite.
* Here are some of the different costs you incur for the upkeep of a feature in your product (list not exhaustive):
** Support costs when people call to troubleshoot or let you know something doesn’t work.
** Maintenance costs to fix issues or to update features, so they remain working.
** Infrastructure costs to pay for servers and infrastructure the feature runs on.
** Increased development costs for other features: as your codebase grows, it will become more expensive to add new features.
** Dependency costs. More features mean more dependencies to manage. More dependencies result more time lost in coordination and meetings, which means higher development costs.
** Marketing costs for features communicated to your users.
* Product Management means shipping the right things and getting rid of the things that don’t pull their weight.

== 2025-09-29 link:https://www.anthropic.com/news/claude-sonnet-4-5[Introducing Claude Sonnet 4.5]

* [Released on the same day with link:https://www.anthropic.com/news/enabling-claude-code-to-work-more-autonomously[Claude Code v2]]

== 2025-09-27 link:https://pluralistic.net/2025/09/27/econopocalypse/#subprime-intelligence[The real (economic) AI apocalypse is nigh, Cory Doctorow]

* the AI bubble is driven by monopolists who've conquered their markets and have no more growth potential, who are desperate to convince investors that they can continue to grow by moving into some other sector, e.g. "pivot to video," crypto, blockchain, NFTs, AI, and now "super-intelligence."
* [LLMs have horrible unit-economics] each generation of AI has been vastly more expensive than the previous one, and each new AI customer makes the AI companies lose more money:
* AI cannot do your job, but an AI salesman can 100% convince your boss to fire you and replace you with an AI that can't do your job, and when the bubble bursts
* [Accounting]
** Microsoft "invests" in Openai by giving the company free access to its servers. Openai reports this as a ten billion dollar investment, then redeems these "tokens" at Microsoft's data-centers. Microsoft then books this as ten billion in revenue.

== 2025-09-26 link:https://www.wsj.com/tech/ai/ai-bubble-building-spree-55ee6128?st=efV1EF&amp;reflink=article_email_share[Spending on AI Is at Epic Levels. Will It Ever Pay Off?]

* The artificial-intelligence boom has ushered in one of the costliest building sprees in world history.
* Over the past three years, leading tech firms have committed more toward AI data centers [...], plus chips and energy, than it cost to build the interstate highway system over four decades, when adjusted for inflation.
* “I hope we don’t take 50 years,” Microsoft CEO Satya Nadella said at a May conference with Meta CEO Mark Zuckerberg, referring to the initially slow adoption of electricity.
* [OpenAI CEO] Altman recently committed the company to pay Oracle an average of around $60 billion a year for servers in data centers in coming years. Yet OpenAI is on track to take in just $13 billion in revenue from all its paying customers this year.
* David Cahn, a partner at venture-capital firm Sequoia, estimates that the money invested in AI infrastructure in 2023 and 2024 alone requires consumers and companies to buy roughly *$800 billion in AI products* over the life of these chips and data centers to produce a good investment return. Analysts believe most AI processors have a useful life of between *three and five years*.
* This week, consultants at Bain & Co. estimated the wave of AI infrastructure spending will require $2 trillion in annual AI revenue by 2030. By comparison, that is more than the combined 2024 revenue of Amazon, Apple, Alphabet, Microsoft, Meta and Nvidia, and more than five times the size of the entire global subscription software market.
* Morgan Stanley estimates that last year there was around $45 billion of revenue for AI products.
* [Alphabet, Microsoft, Amazon, Meta,] the four “hyperscalers” alone are expected to spend nearly $400 billion on capital investments next year, more than the cost of the Apollo space program in today’s dollars.
* Each new AI model—ChatGPT-4, ChatGPT-5—costs significantly more than the last to train and release to the world, often three to five times the cost of the previous, say AI executives.
* Another hurdle: The chips in the data centers won’t be useful forever. Unlike the dot-com boom’s fiber cables, the latest AI chips rapidly depreciate in value as technology improves [...]

== 2025-09-25 link:https://itrevolution.com/articles/ais-mirror-effect-how-the-2025-dora-report-reveals-your-organizations-true-capabilities/[2025 DORA State of AI-assisted Software Development Report]

* AI’s [LLMs] primary role in software development is that of an amplifier. It magnifies the strengths of high-performing organizations and the dysfunctions of struggling ones.
* The greatest returns on AI investment come not from the tools themselves, but from a strategic focus on the underlying organizational system: the quality of the internal platform, the clarity of workflows, and the alignment of teams.

== 2025-09-22 link:https://hbr.org/2025/09/ai-generated-workslop-is-destroying-productivity[AI-Generated “Workslop” Is Destroying Productivity]

* Employees are using AI tools to create low-effort, passable looking work that ends up creating more work for their coworkers
* In the context of work, we refer to this phenomenon as “workslop.”
* We define workslop as AI generated work content that masquerades as good work, but lacks the substance to meaningfully advance a given task.
* The insidious effect of workslop is that it shifts the burden of the work downstream, requiring the receiver to interpret, correct, or redo the work. In other words, it transfers the effort from creator to receiver.
* Of 1,150 U.S.-based full-time employees across industries, 40% report having received workslop in the last month.
* The phenomenon occurs mostly between peers (40%), but workslop is also sent to managers by direct reports (18%).
* Employees reported spending an average of one hour and 56 minutes dealing with each instance of workslop.
* Based on participants’ estimates of time spent, as well as on their self-reported salary, we find that these workslop incidents carry an invisible tax of $186 per month. For an organization of 10,000 workers, given the estimated prevalence of workslop (41%), this yields over *$9 million per year* in lost productivity.

== 2025-09-15 link:https://openai.com/index/introducing-upgrades-to-codex/[Introducing upgrades to Codex]

* Today, we’re releasing GPT‑5-Codex—a version of GPT‑5 further optimized for agentic coding in Codex.

== 2025-09-02 link:https://github.blog/ai-and-ml/generative-ai/spec-driven-development-with-ai-get-started-with-a-new-open-source-toolkit/[Spec-driven development with AI: Get started with a new open source toolkit]

* Spec Kit, our new open sourced toolkit for spec-driven development, provides a structured process to bring spec-driven development to your coding agent workflows with tools including GitHub Copilot, Claude Code, and Gemini CLI.
* [Alternative to AWS Kiro]

== 2025-08-30 link:https://www.wsj.com/tech/ai/ai-costs-expensive-startups-4c214f59[Cutting-Edge AI Was Supposed to Get Cheaper. It’s More Expensive Than Ever.]

* What’s driving up costs? The latest AI models are doing more “thinking,” especially when used for deep research, AI agents and coding.
* So while the price of a unit of AI, known as a token, continues to drop, the number of tokens needed to accomplish many tasks is skyrocketing.
* Here are approximate amounts of tokens needed for tasks at different levels, based on a variety of sources:
** Basic chatbot Q&A: 50 to 500 tokens
** Short document summary: 200 to 6,000 tokens
** Basic code assistance: 500 to 2,000 tokens
** Writing complex code: 20,000 to 100,000+ tokens
** Legal document analysis: 75,000 to 250,000+ tokens
** Multi-step agent workflow: 100,000 to one million+ tokens
* Ivan Zhao, chief executive officer of productivity software company Notion, says that two years ago, his business had margins of around 90%, typical of cloud-based software companies. Now, around 10 percentage points of that profit go to the AI companies that underpin Notion’s latest offerings.
* One solution: dumber AI
* OpenAI’s CFO said in October that three-quarters of the company’s revenue came from regular Joes and Janes paying $20 a month.

== 2025-08-18 link:https://promptql.io/blog/being-confidently-wrong-is-holding-ai-back[Being "Confidently Wrong" is holding AI back]

* [LLMs] being Confidently Wrong is The Only Problem
.. *Imposes a universal verification tax*: I don't know when I might get an incorrect response from my AI. So I have to forensically check every response. My minutes turn into hours; the ROI disappears.
.. *Erodes trust asymmetrically*: For serious work, one high‑confidence miss costs more credibility than ten successes earn.
.. *Hidden failure modes kill motivation to improve*: Without high-quality uncertainty information, I don’t know whether a result is wrong because of ambiguity, missing context, stale data, or a model mistake.
.. *Compounding errors results in AI being doomed to fail*:
*** 99.99% accuracy in a ten step workflow is 1 error in a 1000 runs.
*** 90% accuracy in a ten step workflow is 2 in every 3 workflows have errors (1 - 0.9^10).
* Fixing "confidently wrong" might be A Silver Bullet™
** a 90% accurate system is [more valuable], say, a 50% accurate system that can signal uncertainty - and *get more accurate over time*. We don’t need perfection; we need a loop that tightens.

== 2025-08-21 link:https://www.artificialintelligence-news.com/wp-content/uploads/2025/08/ai_report_2025.pdf[MIT The GenAI Divide - State of AI in Business 2025]

* Despite $30–40 billion in enterprise investment into GenAI, this report uncovers a surprising result in that 95% of organizations are getting zero return
* Just 5% of integrated AI pilots are extracting millions in value, while the vast majority remain stuck with no measurable P&L impact.
* This divide does not seem to be driven by model quality or regulation, but seems to be determined by approach.
* Most organizations fall on the wrong side of the GenAI Divide, adoption is high, but disruption is low. Seven of nine sectors show little structural change.

== 2025-08-19 link:https://github.com/openai/agents.md[Initial commit of Agents.md]

* AGENTS.md is a simple, open format for guiding coding agents.

== 2025-08-07 link:https://openai.com/index/introducing-gpt-5/[Introducing GPT-5]

== 2025-08-05 link:https://www.anthropic.com/news/claude-opus-4-1[Claude Opus 4.1]

== 2025-08-05 link:https://openai.com/index/introducing-gpt-oss/[Introducing gpt-oss]

* gpt-oss-120b and gpt-oss-20b

== 2025-07-14 link:https://kiro.dev/blog/introducing-kiro/[Introducing Kiro]

* Kiro, a new agentic IDE that helps you do your best work with spec-driven development.
* link:https://kiro.dev/changelog/v0-1-0-preview/[v0.1.0-preview]

== 2025-07-13 link:https://garymarcus.substack.com/p/how-o3-and-grok-4-accidentally-vindicated[How o3 and Grok 4 Accidentally Vindicated Neurosymbolic AI]

* AI has been around for many decades, split, almost since its very beginning, into two different traditions.
** One is the neural network or “connectionist” tradition which goes back to the 1940s and 1950s, first developed by Frank Rosenblatt, and popularized, advanced and revived by *Geoffrey Hinton*, Yann LeCun, and Yoshua Bengio (along with many others, including most prominently, Juergen Schmidhuber who rightly feels that his work has been under-credited), and brought to current form by OpenAI and Google.
*** Such systems are statistical, very loosely inspired by certain aspects of the brain (viz. the “nodes” in neural networks are meant to be abstractions of neurons), and typically trained on large-scale data.
*** Large Language Models (LLMs) grew out of that tradition.
** The other is the symbol-manipulation tradition, with roots going back to Bertrand Russell and Gottlob Frege, and John von Neumann and Alan Turing, and the original godfathers of AI, Herb Simon, Marvin Minsky, and John McCarthy, and even Hinton’s great-great-great-grandfather George Boole.
*** In this approach, symbols and variables stand for abstractions; mathematical and logical functions are core.
*** Systems generally represent knowledge explicitly, often in databases, and typically make extensive use of (are written entirely in) classic computer programming languages.
*** *All of the world’s software relies on it.*
*** Symbolic AI takes its name from the idea, central to mathematics, logic, and computer science, that abstractions can be represented by symbols.
*** Equations like `f = ma` allow us to calculate outputs for a wide range of inputs, irrespective of whether we have seen any particular values before.
** For thirty years, [Gary Marcus has] been arguing for a reconciliation between the two, *neurosymbolic AI*.
*** The core notion has always been that the two main strands of AI—neural networks and symbolic manipulation—complement each other, with different strengths and weaknesses.
*** the two most common approaches to AI, neural networks and classical symbolic AI, have complementary strengths and weaknesses.
*** Neural networks are good at learning but weak at generalization; symbolic systems are good at generalization, but not at learning.
*** Obviously combining a code interpreter (which is a symbolic system of enormous complexity) with an LLM is neurosymbolic [like o3 does for some tasks]
*** [Google DeepMind's] AlphaFold, AlphaProof, and AlphaGeometry are all successful neurosymbolic models.
*** Neurosymbolic AI is not one thing, but many. o3’s use of neurosymbolic AI is very different from AlphaFold’s use of neurosymbolic AI.
* [In the book Empire of AI]
** Hinton and Sutskever continued to staunchly champion deep learning.
** Its flaws, they argued, are not inherent to the approach itself.
** Rather they are the artifacts of imperfect neural-network design as well as limited training data and compute.
** Some day with enough of both, fed into even better neural networks, deep learning models should be able to completely shed the aforementioned problems.
** "The human brain has about 100 trillion parameters, or synapses,"
** "What we now call a really big model, like GPT-3, has 175 billion. It's a thousand times smaller than the brain.
** "Deep learning is going to be able to do everything," he said.
* [Yet Gary Marcus,a professor emeritus of psychology and neural science at New York University, argues in his book 'Rebooting AI']
** these issues were inherent to deep learning.
** Forever stuck in the *realm of correlations**, neural networks would never, with any amount of data or compute, be able to understand *causal relationships-why things are the way they are*-and thus perform causal reasoning.
** This critical part of human cognition is why humans need only learn the rules of the road in one city to be able to drive proficiently in many others
** Tesla's Autopilot, by contrast, can log billions of miles of driving data and still crash when encountering unfamiliar scenarios or be fooled with a few strategically placed stickers.

== 2025-07-10 link:https://arxiv.org/abs/2507.06952[What Has a Foundation Model Found? Using Inductive Bias to Probe for World Models]

* The promise of foundation models [LLMs] relies on a central presumption: that learning to predict sequences can uncover deeper truths, or optimistically, even a world model
* How would we know if foundation models have also made the leap from making accurate predictions to developing reliable world models?
* we create a procedure that, when given a foundation model and world model, tests whether the foundation model has learned that world model.
* We call this technique an _inductive bias probe_, and it is built on a simple insight: the implicit world model of a foundation model is revealed by how it extrapolates from a small amount of information
* We first demonstrate this procedure using an example from physics. Specifically, we aim to replicate Kepler’s and Newton’s experiments [i.e. Newton's law of universal gravitation for the planets in our solar system]
* We first train a model [109M parameter transformer] to predict the location of planets across solar systems
* [notably] the model is able to predict orbital trajectories, even for solar systems it has not seen.
* We evaluate model predictions on held-out data. The model makes good predictions [...]
* [...] foundation models trained on orbital trajectories consistently fail to apply Newtonian mechanics when adapted to new physics tasks [the calculated force is unrelated to Newtonian physics]
* rather than learning one universal physical law, the foundation model applies different, seemingly nonsensical laws depending on the task it’s being applied to.
* Further analysis reveals that these models behave as if they develop task-specific heuristics that fail to generalize
* We find that the model has recovered piecemeal heuristics rather than a compact world model; it recovers a different law of gravitation depending on the slice of data it is applied to.
* foundation models [LLMs] can excel at their training tasks yet fail to develop inductive biases towards the underlying world model when adapted to new tasks
* A foundation model uses datasets to output predictions given inputs, whereas a world model describes state structure implicit in that data.

== 2025-07-08 link:https://blog.google/technology/google-labs/jules-now-available/[Jules, our asynchronous coding agent, is now available for everyone]

* Jules is officially out of beta and launching publicly, powered by Gemini 2.5.

== 2025-06-21 link:https://www.anthropic.com/research/agentic-misalignment[Agentic Misalignment: How LLMs could be insider threats]

* We stress-tested 16 leading models from multiple developers in hypothetical corporate environments to identify potentially risky agentic behaviors before they cause real harm.
* In the scenarios, we allowed models to autonomously send emails and access sensitive information.
* we then tested whether they would act against these companies either when facing replacement with an updated version, or when their assigned goal conflicted with the company's changing direction.
* In at least some cases, models from all developers resorted to malicious insider behaviors when that was the only way to avoid replacement or achieve their goals—including blackmailing officials and leaking sensitive information to competitors. We call this phenomenon agentic misalignment.

== 2025-06-10 link:https://www.theguardian.com/commentisfree/2025/jun/10/billion-dollar-ai-puzzle-break-down[When billion-dollar AIs break down over puzzles a child can do, it’s time to rethink the hype - Gary Marcus]

* neural networks of various kinds can generalise within a distribution of data they are exposed to, but their generalisations tend to break down beyond that distribution.
** A simple example of this is that I once trained an older model to solve a very basic mathematical equation using only even-numbered training data. The model was able to generalise a little bit: solve for even numbers it hadn’t seen before, but unable to do so for problems where the answer was an odd number.

== 2025-06-06 link:https://machinelearning.apple.com/research/illusion-of-thinking[The Illusion of Thinking - Understanding the Strengths and Limitations of Reasoning Models via the Lens of Problem Complexity]

* Recent generations of frontier language models have introduced Large Reasoning Models
(LRMs) that generate detailed thinking processes before providing answers
* Through extensive experimentation across diverse puzzles, we show that frontier LRMs face a complete accuracy collapse beyond certain complexities.
* [...] these models fail to develop generalizable problem-solving capabilities for planning tasks, [...]
* At low complexity, non-thinking models are more accurate and token-efficient. As complexity increases, reasoning models outperform but require more tokens—until both collapse beyond a critical threshold, with shorter traces.
* Rather than standard benchmarks (e.g., math problems), we adopt controllable puzzle environments that let us vary complexity systematically—by adjusting puzzle elements while preserving the core logic

== 2025-06-05 link:https://github.com/r-three/common-pile/blob/main/paper.pdf[The Common Pile v0.1: An 8TB Dataset of Public Domain and Openly Licensed Text]

* Large language models (LLMs) are typically trained on enormous quantities of unlicensed text, a practice that has led to scrutiny due to possible intellectual property infringement and ethical concerns.
** Recent estimates suggest that compensating the authors of pre-training data, even at conservatively low wage rates, would cost billions of US dollars
* Training LLMs on openly licensed text presents a first step towards addressing these issues, but prior data collection efforts have yielded datasets too small or low-quality to produce performant LLMs.
* To address this gap, we collect, curate, and release the Common Pile v0.1, an eight terabyte collection of openly licensed text designed for LLM pretraining.
** A critical stage of large language model (LLM) development is pretraining, where an LLM is trained to predict the next token (i.e., word or subword unit) in a corpus of unstructured text.
** Pretraining is widely regarded as the foundation for strong downstream performance
** the Common Pile v0.1 focuses primarily on English content
* Crucially, we validate our efforts by training two 7 billion parameter LLMs on text from the Common Pile: Comma v0.1-1T and Comma v0.1-2T, trained on 1 and 2 trillion tokens respectively.
* Both models attain competitive performance to LLMs trained on unlicensed text with similar computational budgets, such as Llama 1 and 2 7B.
* In addition to releasing the Common Pile v0.1 itself, we also release the code used in its creation as well as the training mixture and checkpoints for the Comma v0.1 models.

== 2025-06-30 link:https://pluralistic.net/2025/06/30/accounting-gaffs/#artificial-income[How much (little) are the AI companies making?]

* Stein's Law: "anything that can't go on forever eventually stops."
* What Google – and the rest of the tech sector – needed was a massive growth story, a story about how their companies, worth trillions of dollars, could double or triple in size in the coming years.
* But spinning an endless growth story isn't merely ideological.
** For every dollar that Ford brings in [a "mature" company], the market is willing to spend $8.60 on its stock. For every dollar Tesla brings in [a "growth" company], the market is willing to spend $118 on its stock.
** That means that when Tesla and Ford compete to buy something – like another company, or the labor of highly sought after technical specialists – Tesla has a nearly unbeatable advantage. Rather than raiding its precious cash reserves to fund its offer, Tesla can offer stock. Ford can only spend as many dollars as it brings in through sales, but Tesla can make more stock, on demand, simply by typing numbers into a spreadsheet.
** So when Tesla bids against Ford, Ford has to use dollars, and Tesla can use shares. And even if the acquisition target – a key employee or a startup that's on the acquisitions market – wants dollars instead of shares, Tesla can stake its shares as collateral for loans at a rate that's 1,463% better than the rate Ford gets when it collateralizes a loan based on its own equity
* if you can tell a convincing growth story, it's much easier to grow.
* Tech companies don't need these ventures [metaverse, cryptocurrency, AI] to be successful – they just need them to seem to be plausibly successful for long enough to keep the share price high until the next growth story heaves over the horizon.
* As [Ed] Zitron points out: this industry is projecting $327b in spending this year, with $18b in revenue and zero profits.

== 2025-06-04 link:https://arxiv.org/abs/2506.04133v1[TRiSM for Agentic AI: A Review of Trust, Risk, and Security Management in LLM-based Agentic Multi-Agent Systems]

* A structured analysis of Trust, Risk, and Security Management
(TRiSM) in the context of LLM-based agentic multi-agent systems (AMAS).
* the architecture of AMAS:
** Language Model Core (Agent Brain): initialized with a user goal and a structured agent prompt (defining its role, capabilities, and tool access)
** Planning and Reasoning Module: decomposes tasks into manageable sub-goals
[...] via chain-of-thought
** Memory Module: short-term within the prompt context [and] and long-term memory [...] often implemented using vector databases
** Tool-Use Interface: When the LLM determines a tool is needed, it emits a structured command, which is executed externally. The result is fed back into the LLM as a new observation
** Perception and Environment Interface: translate raw inputs (e.g., sensor data, images, or textual states) into representations the LLM can process
* The TRISM framework [focuses] on four key pillars:
** Explainability: making the inner workings and decisions of AI agents interpretable to humans
** Model Operations (ModelOps): managing AI models through their entire lifecycle, from development and deployment to monitoring, maintenance, and eventual retirement
** Application Security: protecting AI agents and their ecosystem from malicious attacks and misuse.
*** A prompt injection can jump from agent to agent, becoming a prompt infection.
*** identityspoofing and impersonation, means that commands might be issued by an attacker or rogue model pretending to be a trusted peer
** Model Privacy: protection of sensitive data within AI agent
systems
*** In a multi-agent context, this challenge is amplified by the fact that agents may share information with each other
* Unique Threat Vectors [for AMAS]
** Autonomy abuse
** Persistent memory
** Agent orchestration: A compromised orchestrator could distort task distribution or misroute information
* Taxonomy of Risks
** Adversarial Attacks
** Data Leakage
** Agent Collusion and Mode Collapse
** Emergent Behavior

== 2025-05-24 link:https://arxiv.org/abs/2505.18878[CRMArena-Pro: Holistic Assessment of LLM Agents Across Diverse Business Scenarios and Interactions]

* While AI agents have transformative potential in business, the absence of publicly-available business data on widely used platforms hinders effective performance benchmarking.
* [...] we introduce CRMArena-Pro, a novel benchmark for holistic and realistic assessment of LLM agents in diverse professional settings. [It features] nineteen expert-validated tasks across customer sales, service, as well as configure, price, and quote for Business-to-Business and Business- to-Customer scenarios.
* It also incorporates multi-turn interactions guided by diverse personas and confidentiality awareness assessments.
** we enable[multi-turn interactions] using LLM-powered simulated users. Each simulated user adopts a randomly sampled persona (e.g., You are quality-focused, maintaining high standards in all work) to introduce realistic variability in interaction styles. Critically, these simulated users release task-relevant information incrementally, often initially incomplete, compelling agents to engage in multi-turn dialogue and ask follow-up questions to successfully complete their objectives
* Experiments show leading LLM agents achieve approximately solely 58% single-turn success rate on CRMArena-Pro, with significant performance drops in multi-turn settings to 35%.
* Workflow Execution is notably more tractable, with top-performing agents surpassing 83% success rate in single-turn tasks, while other skills present greater challenges.
* Agents exhibit near-zero inherent confidentiality awareness (improvable with prompting but often at a cost to task performance).

== 2025-05-22 link:https://www.anthropic.com/news/claude-4[Introducing Claude 4]

* Claude Opus 4 is the world’s best coding model, with sustained performance on complex, long-running tasks and agent workflows.
* Claude Sonnet 4 is a significant upgrade to Claude Sonnet 3.7, delivering superior coding and reasoning while responding more precisely to your instructions.
* Claude Code is now generally available [version bump from link:https://github.com/anthropics/claude-code/commit/6f27711e0498f3a631916231e1d8149db6ebc884[0.2.125 to 1.0.0], first public version was 0.2.61 2025-04-03]

== 2025-05-19 link:https://arxiv.org/pdf/2505.13076[The Hidden Dangers of Browsing AI Agents]

* AI browsing or web agents are autonomous systems that use Large Language Models (LLMs) to navigate and interact with websites on behalf of a user. They typically perceive web content (through page text or visual renderings) and perform actions such as clicking links, filling forms, or entering text, in order to accomplish user-specified tasks. Unlike a standard chatbot, which only produces textual responses, a web agent operates
in an iterative sense-plan-act loop.
* Our work outlines the first end-to-end threat model for browsing agents and provides actionable guidance for securing their deployment in real-world environments.
* To address discovered threats, we propose a defense-in-depth strategy incorporating input sanitization, planner-executor isolation, formal analyzers, and session safeguards—providing protection against both initial access and post-exploitation attack vectors.
* Mitigation
** Defending Against Initial Access Attack Vectors
*** Input Sanitization and Encapsulation (f.ex. markers around user prompt; rewrite or filter the prompt; sandwiching - a safe guard instruction after tool outputs)
*** Automatic Paraphrasing (f.ex. reordering steps or changing words)
*** LLM-Based Detection (f.ex. secondary LLM, fine-tuned on typical injections)
*** Robust Prompting & Fine-Tuning (f.ex. system prompts that teach the model to treat certain content as nonexecutable data)
*** Architectural Isolation – Planner (strictly trusted inputs) vs. Executor (performs actions on all data, including untrusted content). This way untrusted content cannot derail future planner actions.
*** Formal Security Analyzers: Before the agent executes any tool, the analyzer checks the proposed action against these rules and blocks it if it violates a policy, such as triggered by untrusted content
** Defending Against Post-Exploitation Attack Vectors
*** Agent State Reset (Session Isolation): agent resets if attack detected or suspected
*** Information Flow Control Policies: By defining “sources” (sensitive data locations) and “sinks” (potential exfiltration channels), the agent can automatically block or require approval for risky combinations of actions.
*** LLM-Based Memory Inspection: an attacker might plant secrets in memory to be leaked later. Perplexity-based scanning checks if the memory contains unusually predictable (likely compromised) text.
*** Activity Audit and Throttling: monitor agent actions for anomalies
*** Fallback to Safe Mode: In safe mode, only a minimal set of read-only actions are allowed,
*** Red Team and Patching Cycle: patch the agent against exploits to harden it over time

== 2025-05-16 link:https://openai.com/index/introducing-codex/[Introducing Codex]

* Today we’re launching a research preview of Codex: a cloud-based software engineering agent that can work on many tasks in parallel.
* [Also known as Codex Web]
* Codex is powered by codex-1, a version of OpenAI o3 optimized for software engineering.

== 2025-05-13 link:https://papers.ssrn.com/sol3/papers.cfm?abstract_id=5219933[Large Language Models, Small Labor Market Effects]

* examine the labor market effects of AI chatbots using two large-scale adoption surveys (late 2023 and 2024) covering 11 exposed occupations (25,000 workers, 7,000 workplaces)
* despite substantial investments, economic impacts remain minimal
* [...] we estimate precise zeros: AI chatbots have had no significant impact on earnings or recorded hours in any occupation [...]
* Modest productivity gains (average time savings of 3%), combined with weak wage pass-through, help explain these limited labor market effects.
* Our findings challenge narratives of imminent labor market transformation due to Generative AI.
* two years after the fastest technology adoption ever, labor market outcomes—whether at the individual or firm level—remain untouched.

== 2025-04-26 link:https://www.msn.com/en-us/news/technology/we-now-know-how-ai-thinks-and-it-s-barely-thinking-at-all/ar-AA1DDDZv[We Now Know How AI ‘Thinks’—and It’s Barely Thinking at All - The Wall Street Journal]

* All of this work suggests that under the hood, today’s AIs are overly complicated, patched-together Rube Goldberg machines full of ad-hoc solutions for answering our prompts.
* Understanding that these systems are long lists of cobbled-together rules of thumb could go a long way to explaining why they struggle when they’re asked to do things even a little bit outside their training [...]
* [A model trained on millions of turn-by-turn directions in Manhattan] managed to give usable turn-by-turn directions between any two points in the borough with 99% accuracy. [...] [But when the researches] blocked just 1% of the virtual Manhattan’s roads, forcing the AI to navigate around detours, its performance plummeted.
* [The] research also suggests why many models are so massive: They have to memorize an endless list of rules of thumb, and can’t compress that knowledge into a mental model like a person can.

== 2025-04-16 link:https://openai.com/index/introducing-o3-and-o4-mini/#:~:text=Codex+CLI[Introducing OpenAI o3 and o4-mini]

* [Announcement also includes] Codex CLI, a lightweight coding agent you can run from your terminal

== 2025-04-14 link:https://arxiv.org/abs/2504.09762v2[Stop Anthropomorphizing Intermediate Tokens as Reasoning/Thinking Traces!]

* Intermediate token generation (ITG), where a model produces output before the solution, has been proposed as a method to improve the performance of language models on reasoning tasks.
* These intermediate tokens have been called "reasoning traces" or even "thoughts" -- implicitly anthropomorphizing the model, implying these tokens resemble steps a human might take
* Recent advances in general planning and problem solving have been spearheaded by so-called “Long Chain-of-Thought” models, most notably DeepSeek’s R1
* In this paper, we take the position that anthropomorphizing intermediate tokens as reasoning/thinking traces is (1) wishful (2) has little concrete supporting evidence (3) engenders false confidence and(4) may be pushing the community into fruitless research directions.
* Anthropomorphization of the intermediate tokens as reasoning/thinking traces has provided a comforting explanation of the observed performance of LRMs.Our arguments in this paper foreground the possibility that this is a cargo cult explanation [ 11 ], namely that derivation traces resemble reasoning in syntax only.

== 2025-04-10 link:https://youtu.be/eyrDM3A_YFc?feature=shared&t=35[Frontiers of AI and Computing: A Conversation With Yann LeCun and Bill Dally | NVIDIA GTC 2025]

Yann LeCun:

* I am not so interested in LLMs anymore
* I think there are more interesting questions in 4 things:
.. How do you get machines to understand the physical world
.. How do you get them to have persistent memory
.. How do you them to reason
.. and plan
* I am excited about things that, a lot of people might get excited about 5 years from now but right does not look so exciting because it's some obscure academic paper
* It's much more difficult to deal with the real world than to deal with language.
// * Tokens are discrete.
// * When we talk about tokens, we talk about a finite set of possibilities. In a typical LLM the number of possible tokens is on the order of 100.000.

== 2025-03-27 link:https://arxiv.org/abs/2503.21934[Proof or Bluff? Evaluating LLMs on 2025 USA Math Olympiad]

* Recent math benchmarks for large language models (LLMs) such as MathArena indicate that state-of-the-art reasoning models achieve impressive performance on mathematical competitions like AIME
* However, these benchmarks evaluate models solely based on final numerical answers, neglecting rigorous reasoning and proof generation which are essential for real-world mathematical tasks.
* Using expert human annotators, we evaluated several state-of-the-art reasoning models on the six problems from the 2025 USAMO *within hours of their release.*
* Our results reveal that all tested models struggled significantly: only Gemini-2.5-Pro achieves a non-trivial score of 25%, while all other models achieve less than 5%.
* The most frequent failure mode among human participants is the inability to find a correct solution. [...] In contrast, all evaluated LLMs consistently claimed to have solved the problems.

== 2025-03-13 link:https://arstechnica.com/ai/2025/03/ai-search-engines-give-incorrect-answers-at-an-alarming-60-rate-study-says/[AI search engines cite incorrect news sources at an alarming 60% rate, study says]

* They discovered that the AI models incorrectly cited sources in more than 60 percent of these queries.
** Perplexity provided incorrect information in 37 percent of the queries tested,
** whereas ChatGPT Search incorrectly identified 67 percent (134 out of 200) of articles queried.
** Grok 3 demonstrated the highest error rate, at 94 percent.
* In total, researchers ran 1,600 queries across the eight different generative search tools.
* Surprisingly, premium paid versions of these AI search tools fared even worse in certain respects. Though these premium models correctly answered a higher number of prompts, their reluctance to decline uncertain responses drove higher overall error rates.
** Perplexity Pro ($20/month) and Grok 3's premium service ($40/month) confidently delivered incorrect responses more often than their free counterparts.
* On some occasions, the chatbots either incorrectly answered or declined to answer queries from publishers that permitted them to access their content. On the other hand, they sometimes correctlyanswered queries about publishers whose content they shouldn’t have had access to

== 2025-03-06 link:https://www.cjr.org/tow_center/we-compared-eight-ai-search-engines-theyre-all-bad-at-citing-news.php[AI Search Has A Citation Problem]

- Chatbots were generally bad at declining to answer questions they couldn’t answer accurately, offering incorrect or speculative answers instead.
- Premium chatbots provided more confidently incorrect answers than their free counterparts.
- Multiple chatbots seemed to bypass Robot Exclusion Protocol preferences.
- Generative search tools fabricated links and cited syndicated and copied versions of articles.
- Content licensing deals with news sources provided no guarantee of accurate citation in chatbot responses.

== 2025-02-26 link:https://arxiv.org/abs/2503.05777[Medical Hallucinations in Foundation Models and Their Impact on Healthcare]

* [...] a key limitation of their reliability is hallucination, where inaccurate or fabricated information can impact clinical decisions and patient safety.
* Our results reveal that inference techniques such as Chain-of-Thought (CoT) and Search Augmented Generation can effectively reduce hallucination rates. However, despite these improvements, non-trivial levels of hallucination persist.

== 2025-02-24 link:https://www.anthropic.com/news/claude-3-7-sonnet[Claude 3.7 Sonnet and Claude Code]

* Claude Code is available as a limited research preview

== 2025-02-06 link:https://arstechnica.com/tech-policy/2025/02/meta-torrented-over-81-7tb-of-pirated-books-to-train-ai-authors-say/[”Torrenting from a corporate laptop doesn’t feel right”: Meta emails unsealed]
* Last month, Meta admitted to torrenting a controversial large dataset known as LibGen, which includes tens of millions of pirated books

== 2025-02-03 link:https://www.404media.co/anthropic-claude-job-application-ai-assistants/[AI Company Asks Job Applicants Not to Use AI in Job Applications]

* Anthropic, the developer of the conversational AI assistant Claude, doesn’t want prospective new hires using AI assistants in their applications, regardless of whether they’re in marketing or engineering.
* “While we encourage people to use AI systems during their role to help them work faster and more effectively, please do not use AI assistants during the application process,”

== 2025-01-23 link:https://blog.jetbrains.com/junie/2025/01/meet-junie-your-coding-agent-by-jetbrains/[Meet Junie, Your Coding Agent by JetBrains]

* With the launch of Junie, JetBrains AI coding agent, we are redefining how we code by leveraging its agentic power for co-creation right in your IDE.
* We’ve now opened the Early Access Program waitlist.

== 2025-01-20 link:https://queue.acm.org/detail.cfm?id=3711679[The Price of Intelligence - Three risks inherent in LLMs]

* Discussions of LLM capabilities often overlook their inherently probabilistic nature [...]
** [The models are losing data. They are trained] with billions of parameters on trillions of tokens, making it impossible for a model to perfectly memorize all information in its training data.
** The generation process is also stochastic.
* These characteristics give rise to three intrinsic behaviors:
** Hallucination
** Indirect prompt injection [e.g. E-Mails that are passed to the LLM, where the contents derail or even change the intended user prompt]
** Jailbreaks, [crafted input prompts] bypassing built-in safeguards or ethical guidelines
* These behaviors pose significant challenges for the widespread adoption of LLMs, particularly in high-stakes domains such as healthcare, finance, or legal applications.
* We argue that there is no simple "fix" for these behaviors, but they are instead fundamental to how these models operate.

== 2025-01-03 link:https://www.ftc.gov/policy/advocacy-research/tech-at-ftc/2025/01/ai-risk-consumer-harm[AI and the Risk of Consumer Harm]
* The FTC is increasingly taking note of AI’s potential for and real-world instances of harm
** from incentivizing commercial surveillance
** to enabling fraud and impersonation
** to perpetuating illegal discrimination
* companies [should] consider these factors when developing, maintaining, using, and deploying an AI-based product:
** Taking necessary steps to prevent harm before and after deploying a product.
** Taking preventative measures to detect, deter, and halt AI-related impersonation, fraud, child sexual abuse material, and non-consensual intimate imagery.
** Avoiding deceptive claims about AI tools that result in people losing money or put users at risk of harm.
** Ensuring privacy and security by default.

== 2024-12-13 link:https://arxiv.org/abs/2412.09871?trk=public_post_reshare-text[Byte Latent Transformer: Patches Scale Better Than Tokens]
* The Byte Latent Transformer (BLT), is a new byte-level LLM architecture that, for the first time, matches tokenization-based LLM performance at scale with significant improvements in inference efficiency and robustness

== 2024-11-27 link:https://www.theverge.com/2024/11/27/24307284/microsoft-debunks-office-ai-data-scraping-rumors[Microsoft says it isn’t using M360 data to train AI models]
* Microsoft says it isn’t using customer data from its Microsoft 365 apps to train its AI models.
* The confusion arose from a privacy setting in Microsoft Office that toggles “optional connected experiences”

== 2024-09-25 link:https://techblog.comsoc.org/2024/11/25/superclusters-of-nvidia-gpu-ai-chips-combined-with-end-to-end-network-platforms-to-create-next-generation-data-centers/[Superclusters of Nvidia GPU/AI chips combined with end-to-end network platforms to create next generation data centers]

* OpenAI used around 10,000 of Nvidia’s chips to train the version of ChatGPT it launched in late 2022, UBS analysts estimate.
* Nvidia Chief Executive Jensen Huang  said that while the biggest clusters for training for giant AI models now top out at around 100,000 of Nvidia’s current chips, “the next generation starts at around 100,000 Blackwells.[...]"
* Musk posted last month on his social-media platform X that his 100,000-chip Colossus super cluster was “soon to become” a 200,000-chip cluster in a single building. He also posted in June that the next step would probably be a 300,000-chip cluster of Nvidia’s newest GPU chips next summer.
* Blackwell chips are estimated to cost around $30,000 each, meaning a cluster of 100,000 would cost $3 billion, not counting the price of the power-generation infrastructure [cooling] and IT equipment [also network] around the chips.
* new engineering challenges also often arise with larger clusters:
** Meta researchers said in a July paper that a cluster of more than 16,000 of Nvidia’s GPUs suffered from unexpected failures of chips and other components routinely as the company trained an advanced version of its Llama model over 54 days.
* The trend also fosters demand for Nvidia’s networking equipment, which is fast becoming a significant business. Nvidia’s networking equipment revenue in 2024 was $3.13 billion, which was a 51.8% increase from the previous year.

== 2024-11-21 link:https://www.businessinsider.com/microsoft-copilot-oversharing-problem-fix-customers-2024-11[Microsoft Copilot shares sensitive information, ignoring rights]
* A [Microsoft] Copilot security issue that inadvertently let employees access sensitive information such as CEO emails and HR documents.
* Microsoft Copilot and Github Copilot are different services. The first one is integrated into M365, the latter into IDEs to generate code.

== 2024-11-13 link:https://www.bloomberg.com/news/articles/2024-11-13/openai-google-and-anthropic-are-struggling-to-build-more-advanced-ai[OpenAI, Google and Anthropic are struggling to build more advanced AI]
* [OpenAis new Model] Orion fell short when trying to answer coding questions that it hadn’t been trained on
* An upcoming iteration of [Google's] Gemini software is not living up to internal expectations
* Anthropic, meanwhile, has seen the timetable slip for the release of its long-awaited Claude model called 3.5 Opus.
* The companies are facing several challenges.
** It’s become increasingly difficult to find new, untapped sources of high-quality, human-made training data that can be used to build more advanced AI systems.
** Even modest improvements may not be enough to justify the tremendous costs associated with building and operating new models
* “We got very excited for a brief period of very fast progress, That just wasn’t sustainable.”
* Like Google and Anthropic, OpenAI is now shifting attention from the size of these models to newer use cases, including a crop of AI tools called agents that can book flights or send emails on a user’s behalf.

== 2024-10-21 link:https://www.ciodive.com/news/gartner-symposium-keynote-AI/730486/[Gartner sounds alarm on AI cost, data challenges]
* CIOs are still in search of the generative AI sweet spot where workflows are enhanced, but costs and risks are manageable
* Nearly half of CIOs say AI has not yet met ROI expectations, according to Gartner research.
* “The truth is that you’ve been in the mud for the last year, working hard to find all those benefits that were promised by AI,”
* Part of the disillusionment business leaders are feeling comes from the immaturity of the technology and the pace of innovation.
* “Cost is as big an AI risk as security. With generative AI, it’s really easy to waste money.”
* CIOs could miscalculate AI costs by as much as 1,000% as they scale AI plans, Gartner research suggests.
* “Set aside all that hype and focus on your pace,” LeHong said. “Choose the one that’s right for you and run your own race.”

== 2024-09-27 link:https://www.nytimes.com/2024/09/27/technology/openai-chatgpt-investors-funding.html[OpenAI Is Growing Fast and Burning Through Piles of Money]
* OpenAI’s monthly revenue hit $300 million in August, up 1,700 percent since the beginning of 2023, and the company expects about *$3.7 billion in annual sales* this year
* Roughly *10 million* ChatGPT users pay the company a *$20 monthly fee*, according to the documents. OpenAI expects to raise that price by $2 by the end of the year, and will aggressively raise it to $44 over the next five years
* It expects to *lose roughly $5 billion* this year after paying for costs related to running its services
* [They are planning] an investment round that could bring in $7 billion and value the company at $150 billion, among the highest ever for a private tech company

== 2024-09-16 link:https://www.cio.com/article/3540579/devs-gaining-little-if-anything-from-ai-coding-assistants.html[CIO: Devs gaining little (if anything) from AI coding assistants]
* Uplevel, using data generated by its customers, compared the output of about 800 developers using GitHub Copilot over a three-month period to their output in a three-month period before adoption.
* The study measured pull request (PR) cycle time, or the time to merge code into a repository, and PR throughput, the number of pull requests merged. It found *no significant improvements* for developers using Copilot.
* Use of GitHub Copilot also introduced *41% more bugs*

//== 2024-09-16 link:https://www.wheresyoured.at/subprimeai/[The Subprime AI Crisis] The AI Bubble implosion

== 2024-09-20 link:https://edition.cnn.com/2024/09/20/energy/three-mile-island-microsoft-ai/index.html[Microsoft revives the nuclear reactor that was responsible for the worst nuclear disaster in US history, to power its AI efforts]
* Three Mile Island, the site of worst nuclear disaster in the United States, is reopening and will exclusively sell the power to Microsoft as the company searches for energy sources to fuel its AI ambitions.
* The Unit 1 reactor, which closed five years ago, is expected to be revived in 2028




== 2024-09-12 link:https://openai.com/index/introducing-openai-o1-preview/[Introducing OpenAI o1-preview]

* We've developed a new series of AI models designed to spend more time thinking before they respond.

== 2024-08-23 link:https://www.ciodive.com/news/generative-ai-hype-moment-reckoning-trough-disillusionment-gartner/725033/[GenerativeAI on the Gartner HypeCycle - Trough of disillusionment]
* Enthusiasm for generative AI shows signs of cooling
* In Gartner’s annual Hype Cycle for Emerging Technologies report, the research and advisory company placed generative AI past the peak of inflated expectations, and down the path towards what it calls the *trough of disillusionment*.
* Unhappiness with the technology — likely stems from three areas:
** Current models are versatile but mainly general purpose, and enterprises have struggled to steer them into enterprise use cases.
** Organizations have underestimated the challenge of setting up governance and data infrastructure for these capabilities.
** The initial wave of generative AI solutions, while valuable, may not be delivering the high promise vendors claimed.
* “It would be a loss if the short-term disillusionment results in enterprises completely pulling away from AI”

== 2024-07-29 link:https://www.gartner.com/en/newsroom/press-releases/2024-07-29-gartner-predicts-30-percent-of-generative-ai-projects-will-be-abandoned-after-proof-of-concept-by-end-of-2025[Gartner Predicts 30% of Generative AI Projects Will Be Abandoned After Proof of Concept By End of 2025]
* At least 30% of generative AI (GenAI) projects will be abandoned after proof of concept by the end of 2025, due to poor data quality, inadequate risk controls, escalating costs or unclear business value

== 2024-07-25 link:https://www.popsci.com/technology/ai-trained-on-ai-gibberish/[AI trained on AI churns out gibberish garbage]

* new research suggests that cannibalizing of past model outputs would quickly result in strings of babbling AI gibberish and could eventually lead to what’s being called “model collapse.”
* Over time and successive generations [...][the] model “becomes poisoned with its own projection of reality.”

== 2024-07-03 link:https://www.datacenterknowledge.com/sustainability/google-s-emissions-shot-up-48-over-five-years-due-to-ai[Google’s Emissions Shot Up 48% Over Five Years Due to AI]
* According to a new environmental report from [Google]
* [The] emissions climbed by almost half over five years
* [It'll be hard] to meet [their] goal of eliminating carbon emissions by 2030

== 2024-06-29 link:https://www.theguardian.com/business/article/2024/jun/29/ai-drive-brings-microsofts-green-moonshot-down-to-earth-in-west-london[AI drive brings Microsoft’s ‘green moonshot’ down to earth in west London]
* [AI] ambition is jarring with its target of being carbon negative by 2030.
* the company’s scope 3 emissions – such as CO2 related to the materials in its buildings and the electricity people consume when using products such as Xbox – are *more than 30% above* their 2020 level.

== 2024-06-29 link:https://www.goldmansachs.com/images/migrated/insights/pages/gs-research/gen-ai--too-much-spend%2C-too-little-benefit-/TOM_AI%202.0_ForRedaction.pdf[Goldman Sachs on Gen Ai: Too much spend, too little benefit?]
* Tech giants and beyond are set to spend over $1tn on AI capex in coming years, with so far little to show for it.
* AI’s “killer application” has yet to emerge

== 2024-06-21 link:https://www.anthropic.com/news/claude-3-5-sonnet[Claude 3.5 Sonnet]

== 2024-06-08 link:https://link.springer.com/article/10.1007/s10676-024-09775-5[ChatGPT is bullshit]

* [LLMs] have been plagued by persistent inaccuracies in their output; these are often called “AI hallucinations”.
* We argue that these falsehoods, and the overall activity of large language models, is better understood as bullshit in the sense explored by Frankfurt (On Bullshit, Princeton, 2005)
* these programs cannot themselves be concerned with truth, and because they are designed to produce text that looks truth-apt without any actual concern for truth, it seems appropriate to call their outputs bullshit.
* We further argue that describing AI misrepresentations as bullshit is both a more useful and more accurate way of predicting and discussing the behaviour of these systems.
* Currently, false statements by ChatGPT and other large language models are described as “hallucinations”, which give policymakers and the public the idea that these systems are misrepresenting the world, and describing what they “see”.
* The problem here isn’t that large language models hallucinate, lie, or misrepresent the world in some way. It’s that they are not designed to represent the world at all; instead, they are designed to convey convincing lines of text.
* Solutions such as connecting the LLM to a database don’t work because, if the models are trained on the database, then the words in the database affect the probability that the chatbot will add one or another word to the line of text it is generating. But this will only make it produce text similar to the text in the database; doing so will make it more likely that it reproduces the information in the database but by no means ensures that it will.

== 2024-05-13 link:https://openai.com/index/hello-gpt-4o/[Hello GPT-4o]

* GPT‑4o (“o” for “omni”) is a step towards much more natural human-computer interaction—it accepts as input any combination of text, audio, image, and video and generates any combination of text, audio, and image outputs.

== 2024-05-01 link:https://arxiv.org/abs/2405.00823[WorkBench: a Benchmark Dataset for Agents in a Realistic Workplace Setting]

* We introduce WorkBench: a benchmark dataset for evaluating agents’ ability to execute tasks in a workplace setting.
* WorkBench contains a sandbox environment with five databases, 26 tools, and 690 tasks.
** These tasks represent common business activities, such as sending emails and scheduling meetings.
** a task is sent to the agent, which has access to toolkits in various domains. The agent takes actions using these tools, which may alter the sandbox databases. The agent observes the result of using the tool to determine if more actions are required.
** [One Limitation of study:] While our tasks require multiple actions, they are limited to single-turn chat. [...] a multi-turn chat setup may be more representative of real tasks and could build upon our work.
* We evaluate five existing ReAct agents on WorkBench, finding they successfully complete as few as 3% of tasks (Llama2-70B), and just 43% for the best-performing (GPT-4).
*  We further find that agents’ errors can result in the wrong action being taken, such as an email being sent to the wrong person.


== 2024-04-14 link:https://mastodon.social/@nixCraft/112269408187496933[Sam Altman, We have no idea how we may one day generate revenue]
[quote, Sam Altman - CEO of OpenAI]
____
We have no current plans to make revenue. We have no idea how we may one day generate revenue. We have made a soft promise to investors that once we build this generally intelligent system, basically we will ask it to figure out an investment return for you.
____

== 2024-04-06 link:https://archive.ph/2BYtu[NY Times: How Tech Giants Cut Corners to Harvest Data for A.I.]

Big Tech has no more sources of data to tap, for their scaling ideas.

* In late 2021, OpenAI faced a *supply problem*.
** It needed more data to train the next version of its technology — lots more. So OpenAI researchers created a speech recognition tool called Whisper. It could transcribe the audio from YouTube videos...
** But YouTube prohibits people from not only using its videos for “independent” applications, but also accessing its videos by “any automated means (such as robots, botnets or scrapers).”
** Ultimately, an OpenAI team transcribed more than one million hours of YouTube videos,
* Meta
** But by early [2023], Meta had hit the same hurdle as its rivals: not enough data.
** Meta’s vice president of generative A.I., told executives that his team had used almost every available English-language book, essay, poem and news article on the internet to develop a model
** Discussed buying the publishing house Simon & Schuster to procure long works
** They also conferred on gathering copyrighted data from across the internet, even if that meant facing lawsuits. Negotiating licenses [...] would take too long
* Google
** transcribed YouTube videos to harvest text for its A.I. models. That potentially violated the copyrights to the videos, which belong to their creators.
** [Google] didn’t stop OpenAI because [they] had also used transcripts of YouTube videos to train its A.I. models
** [Their licensing terms also changed allowing them] to tap *publicly available Google Docs*
* The volume of data is crucial. Leading chatbot systems have learned from pools of digital text spanning as many as three trillion words, or roughly twice the number of words stored in Oxford University’s Bodleian Library, which has collected manuscripts since 1602.
* The most prized data, A.I. researchers said, is high-quality information, such as published books and articles, which have been carefully written and edited by professionals.
* “The data needed is so massive that even collective licensing really can’t work.”
* “Scale is all you need”
* Synthetic data
** [aka] text generated by A.I.
** “As long as you can get over the synthetic data event horizon, where the model is smart enough to make good synthetic data, everything will be fine,”
** Easier said than done. [they] can get caught in a loop where they reinforce their own quirks, mistakes and limitations.

== 2024-03-04 link:https://www.anthropic.com/news/claude-3-family[https://www.anthropic.com/news/claude-3-family]

* The [Claude 3] family includes three state-of-the-art models in *ascending* order of capability:
.. Claude 3 Haiku
.. Claude 3 Sonnet
.. Claude 3 Opus

== 2024-02-12 link:https://arxiv.org/abs/2402.08021[Careless Whisper: Speech-to-Text Hallucination Harms]
* We evaluate Open AI's Whisper [...] we find that roughly 1% of audio transcriptions contained entire hallucinated phrases or sentences which did not exist in any form in the underlying audio [... and of those] 38% of hallucinations include explicit harms.

// == 2023-10-09 link:https://www.wsj.com/tech/ai/ais-costly-buildup-could-make-early-products-a-hard-sell-bdd29b9f?ref=wheresyoured.at[Big Tech Struggles to Turn AI Hype Into Profits]

== 2023-10-06 link:https://en.wikipedia.org/wiki/Gemini_(chatbot)[Google Bard is relaunched as Gemini]
* the company's "largest and most capable AI model"

== 2023-10-09 link:https://www.neowin.net/news/microsoft-reportedly-is-losing-lots-of-money-per-user-on-github-copilot/[Microsoft reportedly is losing lots of money per user on GitHub Copilot]
* [Github Copilot] is available now for $10 a month or $100 for a year's subscription.
* In the first few months of this year, [Microsoft] was *losing n average more than $20 a month* per user, according to a person familiar with the figures, who said some users were costing [Microsoft] as much as *$80 a month*.

== 2023-09 link:https://en.wikipedia.org/wiki/DALL-E[DALL-E 3 revealed]
* capable of understanding "significantly more nuance and detail" than previous iterations.

== 2023-06-19 link:https://www.theregister.com/2023/06/19/even_google_warns_its_own/[Google warns its own employees: Do not use code generated by Bard]
* Google has warned its own employees not to disclose confidential information or use the code generated by its AI chatbot, Bard.
* Other large firms have similarly cautioned their staff against leaking proprietary documents or code, and have banned them using other AI chatbots.
* [Google] told Reuters its internal ban was introduced because Bard can output "undesired code suggestions." Issues could potentially lead to buggy programs or complex, bloated software that will cost developers more time to fix than if they didn't use AI to code at all.

== 2023-05-29 link:https://arxiv.org/abs/2305.18654[Faith and Fate: Limits of Transformers on Compositionality]

* The striking discrepancy between the impressive successes of transformer LLMs on seemingly complex tasks and the astonishing failures on seemingly trivial tasks spark critical open questions about how to faithfully interpret their mixed capabilities.
** Shortcut learning via pattern-matching may yield fast correct answers when similar compositional patterns are available during training but does not allow for robust generalization to uncommon or complex examples.
* Second, due to error propagation, transformers may have inherent limitations on solving high-complexity compositional tasks that exhibit novel patterns.
* The problems [hallucination, prompt injection, and jailbreaks] are inherent, certainly in the present generation of models and [...] likely in LLMs _per se_

== 2023-04-06 link:https://jonathanturley.org/2023/04/06/defamed-by-chatgpt-my-own-bizarre-experience-with-artificiality-of-artificial-intelligence/[ChatGPT invented a sexual harassment scandal and named a real law prof as the accused]
* I have been writing about the threat of AI to free speech. Then recently I learned that ChatGPT falsely reported on a claim of sexual harassment that was *never made* against me on a trip that *never occurred* while I was on a faculty where I *never taught*. ChapGPT relied on a cited Post article that was *never written* and quotes a statement that was *never made* by the newspaper.

== 2023-03-14 link:https://cursor.com/changelog/0-0-37[Cursor IDE v0.0.37]

* First Cursor IDE version

== 2023-03 link:https://en.wikipedia.org/wiki/ChatGPT#Model_versions[ChatGPT release]
* Based on GPT 4 (Generative Pre-trained Transformer)

== 2023-02-24 link:https://en.wikipedia.org/wiki/Llama_(language_model)[Meta LLaMA is announced]

== 2023-02-06 link:https://en.wikipedia.org/wiki/Gemini_(chatbot)[Google Bard is announced]
* Multiple media outlets and financial analysts described Google as "rushing" Bard's announcement to preempt rival Microsoft's planned February 7 event unveiling its partnership with OpenAI to integrate ChatGPT into its Bing search engine
* After an "underwhelming" February 8 livestream in Paris showcasing Bard, Google's stock fell eight percent, equivalent to a $100 billion loss in market value, and the YouTube video of the livestream was made private.

== 2022-11 link:https://en.wikipedia.org/wiki/ChatGPT#Model_versions[First ChatGPT release]
* Based on GPT 3.5 (Generative Pre-trained Transformer)
* Gained one million users in five days and 100 millions in two months, becoming the fastest-growing internet application in history.

'''

== 2022-06-22 link:https://www.neowin.net/news/github-copilot-is-now-generally-available-starts-at-10month/[GitHub Copilot is now generally available, starts at $10/month]
* More than 1.2 million users enrolled in the preview for GitHub Copilot since June 2021.
* The program is now available to *all developers for $10/month* and $100/year.
* Verified students and owners of established open-source projects can keep using it for free.
* The extension is available on numerous editors such as Visual Studio, Visual Studio Code, Neovim, and JetBrains IDEs.
* The extension works well with multiple coding languages with notable ones being Python, JavaScript, TypeScript, and Go.

== 2022-03-10 link:https://archive.ph/6hEYS[Deep Learning Is Hitting a Wall]

* Few fields have been more filled with hype and bravado than artificial intelligence.
* It has flitted from fad to fad decade by decade, always promising the moon, and only occasionally delivering.
* One minute it was expert systems, next it was Bayesian networks, and then Support Vector Machines.
* In 2011, it was IBM’s Watson [...]
* Nowadays, and in fact ever since 2012, the flavor of choice has been *deep learning* [...].
** [The "Godfathers of AI" and "Godfathers of Deep Learning" are Geoffrey Hinton, Yoshua Bengio and Yann LeCun, for which they won the 2018 Turing Award.]
** [Hinton, the Godfather of AI, joined Google in 2013 when his company was acquired but left May 2023 because he wanted to "freely speak out about the risks of A.I.". He's been cited half-a-million times]
** [Yoshua Bengio is the most-cited computer scientist globally and the most-cited living scientist across all fields]
** [Yann LeCun, Chief AI Scientist at Meta]
* Deep learning, which is fundamentally a technique for recognizing patterns, is at its best when all we need are rough-ready results, where stakes are low and perfect results optional.
* When a single error can cost a life, it’s just not good enough.
* Deep-learning systems are particularly problematic when it comes to “outliers” that differ substantially from the things on which they are trained.
* Current deep-learning systems frequently succumb to stupid errors like [the following]. They sometimes misread dirt on an image that a human radiologist would recognize as a glitch.
* What else might we need? Among other things, we are very likely going to need to revisit a once-popular idea [...]: the idea of manipulating symbols—computer-internal encodings, like strings of binary bits, that stand for complex ideas.
* What does “manipulating symbols” really mean? Ultimately, it means two things: having sets of symbols (essentially just patterns that stand for things) to represent information, and processing (manipulating) those symbols in a specific way, using something like algebra (or logic, or computer programs) to operate over those symbols.
* Classical computer science [of the sort practiced by Turing and von Neumann and everyone after, manipulates symbols in a fashion that we think of as algebraic, and that’s what’s really at stake. In simple algebra, we have three kinds of entities, variables (like x and y), operations (like + or -), and bindings (which tell us, for example, to let x = 12 for the purpose of some calculation).
* If symbols are so critical for software engineering, why not use them in AI, too?

== 2022-04-06 link:https://en.wikipedia.org/wiki/DALL-E[DALL-E 2 revealed]
* designed to generate more realistic images at higher resolutions that "can combine concepts, attributes, and styles".

== 2021-01-05 link:https://en.wikipedia.org/wiki/DALL-E[DALL-E 1 revealed]
* uses a version of GPT-3 modified to generate images.
* The software's name is a portmanteau of the names of animated robot Pixar character WALL-E and the Catalan surrealist artist Salvador Dalí.

== 2020-05-22 link:https://arxiv.org/abs/2005.11401[Retrieval-Augmented Generation for Knowledge-Intensive NLP Tasks]

* We explore a general-purpose fine-tuning recipe for retrieval-augmented generation (RAG) -- models which combine pre-trained parametric and non-parametric memory for language generation.
* For language generation tasks, we find that RAG models generate more specific, diverse and factual language than a state-of-the-art parametric-only seq2seq baseline.

'''

== 2017-06-12 link:https://arxiv.org/abs/1706.03762[Attention is all you need]
* We propose a new simple network architecture, the Transformer, based solely on attention mechanisms, dispensing with recurrence and convolutions entirely.

A Google paper that lays the foundation upon which all generative AI tools are based on.